target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'shared', :path => '../shared'
  pod 'KMPObservableViewModelSwiftUI', '1.0.0-BETA-9'
  pod 'KMPNativeCoroutinesAsync', '1.0.0-ALPHA-39'    # Swift Concurrency implementation
  pod 'KMPNativeCoroutinesCombine', '1.0.0-ALPHA-39'  # Combine implementation
end